services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.directory=/etc/traefik/"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.traefik.address=:8080"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - ./certificates:/etc/certs
    networks:
      - docker_net
  
  faceinsight-dashboard:
    build:
      context: ./Frontend/
      dockerfile: Dockerfile.local
    container_name: faceinsight-dashboard
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/src:/app/src
      - ./Frontend/node_modules:/app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faceinsight.rule=Host(`app.localhost`)"
      - "traefik.http.routers.faceinsight.entrypoints=websecure"
      - "traefik.http.routers.faceinsight.tls=true"
      - "traefik.http.routers.http-faceinsight.rule=Host(`app.localhost`)"
      - "traefik.http.routers.http-faceinsight.entrypoints=web"
      - "traefik.http.services.faceinsight.loadbalancer.server.port=3000"
    env_file:
      - ./Frontend/.env
    networks:
      docker_net:
        aliases:
          - app.localhost

  faceinsight-service:
    build:
      context: ./Backend/
      dockerfile: Dockerfile.local
    container_name: faceinsight-service
    restart: always
    ports:
      - "8088:80"
    env_file:
      ./Backend/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faceinsight-service.rule=Host(`api.localhost`)"
      - "traefik.http.routers.faceinsight-service.entrypoints=websecure"
      - "traefik.http.routers.faceinsight-service.tls=true"
      - "traefik.http.routers.http-faceinsight-service.rule=Host(`api.localhost`)"
      - "traefik.http.routers.http-faceinsight-service.entrypoints=web"
      - "traefik.http.services.faceinsight-service.loadbalancer.server.port=80"
    volumes:
      - ./Backend:/usr/src/app
    networks:
      docker_net:
        aliases:
          - api.localhost

  mongodb:
    image: mongo:5.0.5
    container_name: mongodb
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db-volume:/data/db
    networks:
      - docker_net

networks:
  docker_net:
    name: docker_net
    driver: bridge

volumes:
  db-volume:
