services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.traefik.address=:8080"
    ports:
      - "80:80"
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_net
  
  faceinsight-dashboard:
    build:
      context: ./Frontend/
      dockerfile: Dockerfile.local
    container_name: faceinsight-dashboard
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    volumes:
      - ./Frontend/src:/app/src
      - ./Frontend/node_modules:/app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faceinsight.rule=Host(`app.localhost`)"
      - "traefik.http.services.faceinsight.loadbalancer.server.port=3000"
    env_file:
      - ./Frontend/.env
    networks:
      docker_net:
        aliases:
          - app.localhost

  faceinsight-service:
    build:
      context: ./Backend/
      dockerfile: Dockerfile.local
    container_name: faceinsight-service
    restart: always
    env_file:
      ./Backend/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faceinsight-service.rule=Host(`api.localhost`)"
      - "traefik.http.services.faceinsight-service.loadbalancer.server.port=80"
    volumes:
      - ./Backend:/usr/src/app
    networks:
      docker_net:
        aliases:
          - api.localhost

  mongodb:
    image: mongo:5.0.5
    container_name: mongodb
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db-volume:/data/db
    networks:
      - docker_net

networks:
  docker_net:
    name: docker_net
    driver: bridge

volumes:
  db-volume:
